export const BASE_URL = process.env.NODE_ENV === 'development' ? '/api' : ''
export const PRODUCTS_URL = '/products'
export const SINGLE_PRODUCT_URL = '/product'
export const USERS_URL = '/users'
export const ORDERS_URL = '/orders'
export const PAYPAL_URL = '/config/paypal'
